In [1]:
import numpy as np

In [118]:
# .shape -> shape of matrix
# .ndim -> no of dimensions
# .size -> no of elements
# .astype -> type conversion
# .dtype -> data type of elements


# np.zeros((shape))
# np.ones((shape))
# np.empty((shape))
# np.random.randint(start no, end no, size = (shape))

# np.arange(1,20)
# np.linspace(1,20,10,dtype=int)

# .reshape((shape)) return a copy
# .resize((shape)) inplace reshape karega

# .flat - flatten the array and return flatiter obj
# .ravel() - return a flatten copy and return a array

# x+y
# x-y
# x*y
# x//y
# x@y

# axis = 1 row wise L2R
# axis = 0 column wise T2B
# .sum()
# .cumsum()
# .sort()
# .min()
# .max()


# slicing
# x[:, :] -> all rows all columns
# x[:, 1:] -> all rows skip 0th column
# x[2:, 0] -> from row 2 and 0th column
# x[-1::-1, :] -> rows from bottom to top
# x[:, -1::-1] -> columns from right to left
# x[-1::-1, -1::-1] -> fully invert the matrix
# x[1:, 0] = 0 -> assign the values


# np.vstack - vertically append kr dega 
# np.hstack - horizontally append kr dega 
# np.column_stack - as a new column add kr dega (same as hstack)
# np.row_stack - as a new row add kr dega (same as vstack)
# np.concatinate - work as both column stack nd row stack. use axis=1 for column_stack and 0 for row_stack.

# for 3D matrix use
# np.concate((x, y), axis = 0/1/2) - axis = 0 along the depth, 1 along the rows, 2 along the column


# np.where(condition, if_true, false)


# np.split(array, no_of_sections) - throw error if split not possible
# np.array_split(array, no_of_sec) - wont throw error, instead create empty array
# np.vsplit(...) - vertically split, throw error if split not possible
# np.hsplit(...) - horizontally split, throw error if split not possible

In [127]:
x = np.random.randint(1, 9, (4,5))
x

array([[5, 4, 5, 2, 1],
       [1, 2, 1, 5, 4],
       [5, 2, 1, 4, 7],
       [1, 1, 8, 3, 2]])

In [134]:
np.split(x, indices_or_sections = 2, axis = 0)

[array([[5, 4, 5, 2, 1],
        [1, 2, 1, 5, 4]]),
 array([[5, 2, 1, 4, 7],
        [1, 1, 8, 3, 2]])]

In [137]:
np.array_split(x, indices_or_sections = 3, axis = 0)

[array([[5, 4, 5, 2, 1],
        [1, 2, 1, 5, 4]]),
 array([[5, 2, 1, 4, 7]]),
 array([[1, 1, 8, 3, 2]])]

In [138]:
np.vsplit(x, indices_or_sections = 2)

[array([[5, 4, 5, 2, 1],
        [1, 2, 1, 5, 4]]),
 array([[5, 2, 1, 4, 7],
        [1, 1, 8, 3, 2]])]

In [139]:
np.hsplit(x, 5)

[array([[5],
        [1],
        [5],
        [1]]),
 array([[4],
        [2],
        [2],
        [1]]),
 array([[5],
        [1],
        [1],
        [8]]),
 array([[2],
        [5],
        [4],
        [3]]),
 array([[1],
        [4],
        [7],
        [2]])]

In [117]:
x = np.random.randint(1, 9, (3,3))
x

array([[2, 6, 7],
       [1, 6, 5],
       [5, 5, 4]])

In [122]:
y = np.zeros((3,3), dtype=int)

In [123]:
np.concatenate((x, y), axis = 1)

array([[2, 6, 7, 0, 0, 0],
       [1, 6, 5, 0, 0, 0],
       [5, 5, 4, 0, 0, 0]])

In [124]:
np.concatenate((x, y), axis = 0)

array([[2, 6, 7],
       [1, 6, 5],
       [5, 5, 4],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [98]:
x = np.random.randint(1, 9, (10, 4))
x

array([[6, 4, 7, 5],
       [3, 5, 1, 5],
       [6, 2, 1, 5],
       [1, 6, 1, 1],
       [5, 1, 4, 8],
       [8, 5, 3, 1],
       [3, 6, 5, 3],
       [6, 5, 7, 2],
       [5, 8, 3, 6],
       [4, 8, 2, 1]])

In [109]:
y = np.zeros(10, dtype=int)

In [114]:
np.hstack((x, np.zeros((10, 1), dtype=int)))

array([[6, 4, 7, 5, 0],
       [3, 5, 1, 5, 0],
       [6, 2, 1, 5, 0],
       [1, 6, 1, 1, 0],
       [5, 1, 4, 8, 0],
       [8, 5, 3, 1, 0],
       [3, 6, 5, 3, 0],
       [6, 5, 7, 2, 0],
       [5, 8, 3, 6, 0],
       [4, 8, 2, 1, 0]])

In [115]:
np.column_stack((x, np.zeros((10, 1), dtype=int)))

array([[6, 4, 7, 5, 0],
       [3, 5, 1, 5, 0],
       [6, 2, 1, 5, 0],
       [1, 6, 1, 1, 0],
       [5, 1, 4, 8, 0],
       [8, 5, 3, 1, 0],
       [3, 6, 5, 3, 0],
       [6, 5, 7, 2, 0],
       [5, 8, 3, 6, 0],
       [4, 8, 2, 1, 0]])

In [111]:
np.vstack((x, np.zeros((1, 4), dtype=int)))

array([[6, 4, 7, 5],
       [3, 5, 1, 5],
       [6, 2, 1, 5],
       [1, 6, 1, 1],
       [5, 1, 4, 8],
       [8, 5, 3, 1],
       [3, 6, 5, 3],
       [6, 5, 7, 2],
       [5, 8, 3, 6],
       [4, 8, 2, 1],
       [0, 0, 0, 0]])

In [77]:
x.sum(axis=1)

array([19, 11, 12])

In [67]:
x.reshape((2, 2, 4))

array([[[7, 4, 6, 3],
        [2, 7, 1, 8]],

       [[4, 4, 4, 7],
        [4, 4, 7, 4]]])

In [69]:
x.resize((2, 4, 2))

In [70]:
x

array([[[7, 4],
        [6, 3],
        [2, 7],
        [1, 8]],

       [[4, 4],
        [4, 7],
        [4, 4],
        [7, 4]]])

In [71]:
x.ravel()

array([7, 4, 6, 3, 2, 7, 1, 8, 4, 4, 4, 7, 4, 4, 7, 4])

In [22]:
x = np.random.randint(1, 20, size = (3,4))

In [23]:
x

array([[15, 16,  5, 17],
       [15, 10, 19,  1],
       [ 4, 10, 14, 16]])

In [39]:
np.vstack((x, np.zeros((1,4)))).astype(int)

array([[15, 16,  5, 17],
       [15, 10, 19,  1],
       [ 4, 10, 14, 16],
       [ 0,  0,  0,  0]])

In [36]:
np.hstack((x, np.ones((3,1), dtype=int)))

array([[15, 16,  5, 17,  1],
       [15, 10, 19,  1,  1],
       [ 4, 10, 14, 16,  1]])